// frontend/src/components/workspace/scheduled-task-schedule-input.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useI18n } from "@/core/i18n/hooks";
import {
  describeSchedule,
  pad2,
  parseCron,
  serializeCron,
  utcToZonedLocalInput,
  WEEKDAYS,
  zonedLocalToUtcIso,
  type CronParts,
  type CronPreset,
  type ScheduleLocale,
  type Weekday,
} from "@/core/scheduled-tasks/cron";

export type ScheduleValue = {
  schedule_type: "once" | "cron";
  schedule_spec: { cron?: string; run_at?: string };
  timezone: string;
};

const PRESETS: CronPreset[] = [
  "hourly",
  "daily",
  "weekly",
  "monthly",
  "custom",
];

const FALLBACK_TIMEZONES = [
  "UTC",
  "Asia/Shanghai",
  "Asia/Tokyo",
  "Asia/Singapore",
  "Europe/London",
  "Europe/Berlin",
  "America/New_York",
  "America/Chicago",
  "America/Los_Angeles",
];

function detectBrowserTimezone(): string {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (typeof tz === "string" && tz.length > 0) {
      return tz;
    }
  } catch {
    // resolvedOptions unavailable
  }
  return "UTC";
}

function timezoneOptions(): string[] {
  const supported = (
    Intl as unknown as {
      supportedValuesOf?: (key: string) => string[] | undefined;
    }
  ).supportedValuesOf?.("timeZone");
  if (Array.isArray(supported) && supported.length > 0) {
    return supported;
  }
  return FALLBACK_TIMEZONES;
}

const TIMEZONE_OPTIONS = timezoneOptions();

export function ScheduledTaskScheduleInput({
  initial,
  onChange,
  scheduleTypeLocked = false,
}: {
  initial: ScheduleValue;
  onChange: (value: ScheduleValue) => void;
  scheduleTypeLocked?: boolean;
}) {
  const { t, locale } = useI18n();
  const schedLocale: ScheduleLocale = locale.startsWith("zh") ? "zh" : "en";
  const labels = t.scheduledTasks;

  const [scheduleType, setScheduleType] = useState<"once" | "cron">(
    initial.schedule_type,
  );
  const [preset, setPreset] = useState<CronPreset>(
    () => parseCron(initial.schedule_spec.cron ?? "0 9 * * *").preset,
  );
  const [parts, setParts] = useState<CronParts>(
    () => parseCron(initial.schedule_spec.cron ?? "0 9 * * *").parts,
  );
  const [runAtLocal, setRunAtLocal] = useState<string>(
    initial.schedule_type === "once" && initial.schedule_spec.run_at
      ? utcToZonedLocalInput(
          initial.schedule_spec.run_at,
          initial.timezone || "UTC",
        )
      : "",
  );
  const [timezone, setTimezone] = useState<string>(
    initial.timezone || detectBrowserTimezone(),
  );

  // Hold the latest onChange in a ref so the effect below does not depend on
  // it. This avoids a re-render loop: if the parent passes an inline
  // onChange (new reference each render), depending on it directly would
  // re-fire the effect every render and call onChange again, looping.
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  // Emit on every change including mount. On mount this syncs the parent with
  // the browser-detected timezone and the canonicalized cron, so the submitted
  // value always matches what the user sees in the preview.
  useEffect(() => {
    if (scheduleType === "once") {
      const runAt = runAtLocal ? zonedLocalToUtcIso(runAtLocal, timezone) : "";
      onChangeRef.current({
        schedule_type: "once",
        schedule_spec: runAt ? { run_at: runAt } : {},
        timezone,
      });
      return;
    }
    const cron =
      preset === "custom" ? (parts.raw ?? "") : serializeCron(preset, parts);
    onChangeRef.current({
      schedule_type: "cron",
      schedule_spec: cron ? { cron } : {},
      timezone,
    });
  }, [scheduleType, preset, parts, runAtLocal, timezone]);

  function updateParts(patch: Partial<CronParts>) {
    setParts((prev) => ({ ...prev, ...patch }));
  }

  function changePreset(next: CronPreset) {
    setParts((prev) => {
      const merged = { ...prev };
      if (next === "weekly" && (merged.weekdays ?? []).length === 0) {
        merged.weekdays = ["mon"];
      }
      if (next === "monthly" && merged.dayOfMonth == null) {
        merged.dayOfMonth = 1;
      }
      if (next === "custom" && !merged.raw) {
        merged.raw = serializeCron("daily", prev);
      }
      return merged;
    });
    setPreset(next);
  }

  function toggleWeekday(w: Weekday) {
    setParts((prev) => {
      const set = new Set(prev.weekdays ?? []);
      if (set.has(w)) {
        if (set.size <= 1) {
          return prev;
        }
        set.delete(w);
      } else {
        set.add(w);
      }
      return { ...prev, weekdays: WEEKDAYS.filter((d) => set.has(d)) };
    });
  }

  // `Intl.supportedValuesOf("timeZone")` does not contain "UTC", while
  // `resolvedOptions().timeZone` returns exactly that on a UTC host — and a
  // stored task may carry any zone the Gateway accepted. A value with no
  // matching item renders the trigger blank, so keep the current one in the
  // list instead of dropping it.
  const timezoneChoices = useMemo(
    () =>
      timezone && !TIMEZONE_OPTIONS.includes(timezone)
        ? [timezone, ...TIMEZONE_OPTIONS]
        : TIMEZONE_OPTIONS,
    [timezone],
  );

  const preview = describeSchedule(
    { scheduleType, preset, parts, runAtLocal, timezone },
    schedLocale,
  );

  return (
    <div className="flex flex-col gap-2" data-testid="schedule-input">
      {!scheduleTypeLocked && (
        <div className="flex flex-wrap gap-2">
          <Button
            variant={scheduleType === "cron" ? "default" : "outline"}
            size="sm"
            onClick={() => setScheduleType("cron")}
            aria-pressed={scheduleType === "cron"}
          >
            {labels.scheduleType.cron}
          </Button>
          <Button
            variant={scheduleType === "once" ? "default" : "outline"}
            size="sm"
            onClick={() => setScheduleType("once")}
            aria-pressed={scheduleType === "once"}
          >
            {labels.scheduleType.once}
          </Button>
        </div>
      )}

      {scheduleType === "cron" ? (
        <>
          <Select
            value={preset}
            onValueChange={(v) => changePreset(v as CronPreset)}
          >
            <SelectTrigger className="w-full" data-testid="schedule-preset">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {PRESETS.map((p) => (
                <SelectItem key={p} value={p}>
                  {labels.preset[p]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {preset === "hourly" && (
            <Input
              type="number"
              min={0}
              max={59}
              value={parts.minute ?? 0}
              onChange={(e) => updateParts({ minute: Number(e.target.value) })}
              aria-label={labels.fields.minute}
            />
          )}

          {(preset === "daily" ||
            preset === "weekly" ||
            preset === "monthly") && (
            <Input
              type="time"
              value={`${pad2(parts.hour ?? 9)}:${pad2(parts.minute ?? 0)}`}
              onChange={(e) => {
                const [h, m] = e.target.value.split(":").map(Number);
                updateParts({ hour: h, minute: m });
              }}
              aria-label={labels.fields.time}
            />
          )}

          {preset === "weekly" && (
            <div className="flex flex-wrap gap-1">
              <span className="text-muted-foreground w-full text-sm">
                {labels.fields.weekday}
              </span>
              {WEEKDAYS.map((w) => {
                const active = (parts.weekdays ?? []).includes(w);
                return (
                  <Button
                    key={w}
                    variant={active ? "default" : "outline"}
                    size="sm"
                    onClick={() => toggleWeekday(w)}
                    aria-pressed={active}
                  >
                    {labels.weekdays[w]}
                  </Button>
                );
              })}
            </div>
          )}

          {preset === "monthly" && (
            <Input
              type="number"
              min={1}
              max={31}
              value={parts.dayOfMonth ?? 1}
              onChange={(e) =>
                updateParts({ dayOfMonth: Number(e.target.value) })
              }
              aria-label={labels.fields.dayOfMonth}
            />
          )}

          {preset === "custom" && (
            <div className="flex flex-col gap-1">
              <Input
                value={parts.raw ?? ""}
                onChange={(e) => updateParts({ raw: e.target.value })}
                placeholder={labels.fields.cronPlaceholder}
                aria-label={labels.fields.cron}
              />
              <a
                href="https://crontab.guru/"
                target="_blank"
                rel="noreferrer"
                className="text-muted-foreground text-xs hover:underline"
              >
                {labels.cronHelp} ↗
              </a>
            </div>
          )}
        </>
      ) : (
        <Input
          type="datetime-local"
          value={runAtLocal}
          onChange={(e) => setRunAtLocal(e.target.value)}
          aria-label={labels.fields.runAt}
        />
      )}

      <Select value={timezone} onValueChange={setTimezone}>
        <SelectTrigger className="w-full" data-testid="schedule-timezone">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {timezoneChoices.map((tzOption) => (
            <SelectItem key={tzOption} value={tzOption}>
              {tzOption}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      <div
        className="text-muted-foreground text-sm"
        data-testid="schedule-preview"
      >
        {preview}
      </div>
    </div>
  );
}

// frontend-vue/app/components/workspace/scheduled-tasks/ScheduledTaskScheduleInput.vue
<script setup lang="ts">
/*
  【文件职责】     编辑 once/cron 两种 Gateway schedule，并提供五种 cron preset、时区和预览。
  【架构位置】     L3 scheduled-task form component
  【主要导出】     默认 ScheduledTaskScheduleInput
  【依赖关系】     scheduled-tasks cron/schedule · ui/button · ui/select · app i18n
  【边界与注意】   接口是 `initial` + `@change`，**不是** v-model：与
                   frontend/src/components/workspace/scheduled-task-schedule-input.tsx
                   一样，组件自己持有 preset/parts/时区，把它们规范化成一个
                   `ScheduleValue` 发出去，包括挂载那一次——挂载时发出的那一次正是
                   「时区留空则用浏览器时区」「cron 写回规范形式」生效的地方。
                   要重置（应用 recipe、换选中任务）由调用方换 `key` 重新挂载，同 React。

                   `run_at` 发出去的是 **UTC ISO**，不是 datetime-local 的墙上时间：
                   转换在这里发生，payload 构建那一层只做搬运。此前 Vue 把墙上时间留在
                   模型里、在 form.ts 边界转换，还额外做了「这个本地时间在该时区不存在」
                   和「必须是将来」两条本地校验——React 没有这两条，它把这类输入直接
                   POST 给 Gateway，由 422 的 detail 回来。两条校验各自带着一句写死的
                   英文文案，两个应用在同一次误操作上会说不同的话。

                   `hourly` 只给分钟输入框，其余 preset 给一个 `type="time"`：一个时间
                   选择器，不是「小时」+「分钟」两个数字框。数字框那版把 `fields.time`
                   («Time») 挂在 0~23 的小时框上，读屏器会念出一个叫「时间」的微调框。
*/
import { computed, ref, watch } from "vue";

import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  describeSchedule,
  pad2,
  parseCron,
  serializeCron,
  utcToZonedLocalInput,
  WEEKDAYS,
  zonedLocalToUtcIso,
  type CronParts,
  type CronPreset,
  type ScheduleLocale,
  type Weekday,
} from "@/core/scheduled-tasks/cron";
import {
  detectBrowserTimezone,
  timezoneOptions,
  type ScheduleValue,
} from "@/core/scheduled-tasks/schedule";

const PRESETS: CronPreset[] = [
  "hourly",
  "daily",
  "weekly",
  "monthly",
  "custom",
];

const TIMEZONE_OPTIONS = timezoneOptions();

const props = withDefaults(
  defineProps<{
    initial: ScheduleValue;
    scheduleTypeLocked?: boolean;
  }>(),
  { scheduleTypeLocked: false },
);
const emit = defineEmits<{ change: [value: ScheduleValue] }>();
const { $i18n } = useNuxtApp();

const labels = computed(() => $i18n.t.value.scheduledTasks);
const scheduleLocale = computed<ScheduleLocale>(() =>
  $i18n.locale.value.startsWith("zh") ? "zh" : "en",
);

const initialCron = parseCron(props.initial.schedule_spec.cron ?? "0 9 * * *");
const scheduleType = ref<"once" | "cron">(props.initial.schedule_type);
const preset = ref<CronPreset>(initialCron.preset);
const parts = ref<CronParts>(initialCron.parts);
const runAtLocal = ref(
  props.initial.schedule_type === "once" && props.initial.schedule_spec.run_at
    ? utcToZonedLocalInput(
        props.initial.schedule_spec.run_at,
        props.initial.timezone || "UTC",
      )
    : "",
);
const timezone = ref(props.initial.timezone || detectBrowserTimezone());

watch(
  [scheduleType, preset, parts, runAtLocal, timezone],
  () => {
    if (scheduleType.value === "once") {
      const runAt = runAtLocal.value
        ? zonedLocalToUtcIso(runAtLocal.value, timezone.value)
        : "";
      emit("change", {
        schedule_type: "once",
        schedule_spec: runAt ? { run_at: runAt } : {},
        timezone: timezone.value,
      });
      return;
    }
    const cron =
      preset.value === "custom"
        ? (parts.value.raw ?? "")
        : serializeCron(preset.value, parts.value);
    emit("change", {
      schedule_type: "cron",
      schedule_spec: cron ? { cron } : {},
      timezone: timezone.value,
    });
  },
  { deep: true, immediate: true },
);

function updateParts(patch: Partial<CronParts>) {
  parts.value = { ...parts.value, ...patch };
}

function changePreset(next: CronPreset) {
  const merged = { ...parts.value };
  if (next === "weekly" && (merged.weekdays ?? []).length === 0) {
    merged.weekdays = ["mon"];
  }
  if (next === "monthly" && merged.dayOfMonth == null) {
    merged.dayOfMonth = 1;
  }
  if (next === "custom" && !merged.raw) {
    merged.raw = serializeCron("daily", parts.value);
  }
  parts.value = merged;
  preset.value = next;
}

/** 最后一个星期几不能取消：cron 的 day-of-week 字段不能为空。 */
function toggleWeekday(day: Weekday) {
  const selected = new Set(parts.value.weekdays ?? []);
  if (selected.has(day)) {
    if (selected.size <= 1) return;
    selected.delete(day);
  } else {
    selected.add(day);
  }
  updateParts({
    weekdays: WEEKDAYS.filter((candidate) => selected.has(candidate)),
  });
}

function setTime(value: string) {
  const [hour, minute] = value.split(":").map(Number);
  updateParts({ hour, minute });
}

const timeValue = computed(
  () => `${pad2(parts.value.hour ?? 9)}:${pad2(parts.value.minute ?? 0)}`,
);
const preview = computed(() =>
  describeSchedule(
    {
      scheduleType: scheduleType.value,
      preset: preset.value,
      parts: parts.value,
      runAtLocal: runAtLocal.value,
      timezone: timezone.value,
    },
    scheduleLocale.value,
  ),
);
const inputClass =
  "placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] md:text-sm";
</script>

<template>
  <div class="flex flex-col gap-2" data-testid="schedule-input">
    <div
      v-if="!scheduleTypeLocked"
      class="flex flex-wrap gap-2"
      data-testid="scheduled-task-schedule-type"
    >
      <Button
        :variant="scheduleType === 'cron' ? 'default' : 'outline'"
        size="sm"
        @click="scheduleType = 'cron'"
      >
        {{ labels.scheduleType.cron }}
      </Button>
      <Button
        :variant="scheduleType === 'once' ? 'default' : 'outline'"
        size="sm"
        @click="scheduleType = 'once'"
      >
        {{ labels.scheduleType.once }}
      </Button>
    </div>

    <template v-if="scheduleType === 'cron'">
      <Select
        :model-value="preset"
        @update:model-value="changePreset($event as CronPreset)"
      >
        <SelectTrigger class="w-full" data-testid="schedule-preset">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          <SelectItem v-for="kind in PRESETS" :key="kind" :value="kind">
            {{ labels.preset[kind] }}
          </SelectItem>
        </SelectContent>
      </Select>

      <input
        v-if="preset === 'hourly'"
        type="number"
        min="0"
        max="59"
        :class="inputClass"
        :value="parts.minute ?? 0"
        :aria-label="labels.fields.minute"
        @input="
          updateParts({
            minute: Number(($event.target as HTMLInputElement).value),
          })
        "
      />

      <input
        v-if="preset === 'daily' || preset === 'weekly' || preset === 'monthly'"
        type="time"
        :class="inputClass"
        :value="timeValue"
        :aria-label="labels.fields.time"
        @input="setTime(($event.target as HTMLInputElement).value)"
      />

      <div v-if="preset === 'weekly'" class="flex flex-wrap gap-1">
        <span class="text-muted-foreground w-full text-sm">
          {{ labels.fields.weekday }}
        </span>
        <Button
          v-for="day in WEEKDAYS"
          :key="day"
          :variant="parts.weekdays?.includes(day) ? 'default' : 'outline'"
          size="sm"
          :aria-pressed="Boolean(parts.weekdays?.includes(day))"
          @click="toggleWeekday(day)"
        >
          {{ labels.weekdays[day] }}
        </Button>
      </div>

      <input
        v-if="preset === 'monthly'"
        type="number"
        min="1"
        max="31"
        :class="inputClass"
        :value="parts.dayOfMonth ?? 1"
        :aria-label="labels.fields.dayOfMonth"
        @input="
          updateParts({
            dayOfMonth: Number(($event.target as HTMLInputElement).value),
          })
        "
      />

      <div v-if="preset === 'custom'" class="flex flex-col gap-1">
        <input
          data-testid="scheduled-task-custom-cron"
          :class="inputClass"
          :value="parts.raw ?? ''"
          :placeholder="labels.fields.cronPlaceholder"
          :aria-label="labels.fields.cron"
          @input="
            updateParts({ raw: ($event.target as HTMLInputElement).value })
          "
        />
        <a
          href="https://crontab.guru/"
          target="_blank"
          rel="noreferrer"
          class="text-muted-foreground text-xs hover:underline"
        >
          {{ labels.cronHelp }} ↗
        </a>
      </div>
    </template>
    <input
      v-else
      data-testid="scheduled-task-run-at"
      type="datetime-local"
      :class="inputClass"
      :value="runAtLocal"
      :aria-label="labels.fields.runAt"
      @input="runAtLocal = ($event.target as HTMLInputElement).value"
    />

    <Select v-model="timezone">
      <SelectTrigger class="w-full" data-testid="schedule-timezone">
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        <SelectItem
          v-for="option in TIMEZONE_OPTIONS"
          :key="option"
          :value="option"
        >
          {{ option }}
        </SelectItem>
      </SelectContent>
    </Select>

    <div class="text-muted-foreground text-sm" data-testid="schedule-preview">
      {{ preview }}
    </div>
  </div>
</template>
