// frontend/src/app/auth/callback/page.tsx
"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";

import { resolveAuthNextPath } from "@/core/auth/next-path";

/*
  This page lives at `src/app/auth/callback/` and NOT under the `(auth)` route
  group on purpose — see `src/app/auth/layout.tsx`. Moving it back would make
  the `next` handling below dead code again, because the group layout redirects
  authenticated users to `/workspace` before this component ever mounts.
  `tests/unit/app/auth-callback-route.test.ts` pins the placement.
*/
export default function AuthCallbackPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<"loading" | "success" | "error">(
    "loading",
  );
  const calledRef = useRef(false);

  const doAuthCheck = useCallback(async () => {
    if (calledRef.current) return;
    calledRef.current = true;

    const next = resolveAuthNextPath(searchParams.get("next"));

    try {
      const res = await fetch("/api/v1/auth/me", { credentials: "include" });

      if (res.ok) {
        setStatus("success");
        // Small delay so the user sees the success message
        setTimeout(() => router.replace(next), 300);
      } else {
        setStatus("error");
        setTimeout(() => router.replace("/login?error=sso_failed"), 1500);
      }
    } catch {
      setStatus("error");
      setTimeout(() => router.replace("/login?error=sso_failed"), 1500);
    }
  }, [searchParams, router]);

  useEffect(() => {
    void doAuthCheck();
  }, [doAuthCheck]);

  return (
    <div className="bg-background relative flex min-h-screen items-center justify-center">
      <div className="text-center">
        {status === "loading" && (
          <>
            <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-current border-t-transparent" />
            <p className="text-muted-foreground">Signing you in...</p>
          </>
        )}
        {status === "success" && (
          <p className="text-muted-foreground">Redirecting...</p>
        )}
        {status === "error" && (
          <p className="text-muted-foreground">
            Authentication failed. Redirecting to login...
          </p>
        )}
      </div>
    </div>
  );
}

// frontend-vue/app/pages/auth/callback.vue
<!--
  【文件职责】     验证 OIDC callback session、显示明确状态并执行安全 replace 跳转。
  【对应 frontend/】 frontend/src/app/(auth)/auth/callback/page.tsx
  【架构位置】     L3
  【主要导出】     /auth/callback 页面
  【依赖关系】     auth session Vue Query · callback pure decision · auth layout
  【边界与注意】   双入口 provider 逻辑仍归 Gateway；本页只验证 cookie session 与 safe next。
-->

<script setup lang="ts">
import { onMounted, onScopeDispose, ref } from "vue";
import { useQueryClient } from "@tanstack/vue-query";

import { resolveAuthCallback } from "@/core/auth/callback";
import { authSessionQueryOptions } from "@/core/auth/session-query";

definePageMeta({ layout: "auth" });

const route = useRoute();
const queryClient = useQueryClient();
const status = ref<"loading" | "success" | "unauthenticated" | "unavailable">(
  "loading",
);
let redirectTimer: number | undefined;

onMounted(async () => {
  const session = await queryClient.fetchQuery(authSessionQueryOptions());
  const resolution = resolveAuthCallback(
    session,
    typeof route.query.next === "string" ? route.query.next : null,
  );
  status.value = resolution.status;
  redirectTimer = window.setTimeout(
    () => void navigateTo(resolution.location, { replace: true }),
    resolution.status === "success" ? 300 : 1_500,
  );
});

onScopeDispose(() => {
  if (redirectTimer !== undefined) window.clearTimeout(redirectTimer);
});
</script>

<template>
  <div
    class="bg-background relative flex min-h-screen items-center justify-center"
  >
    <div class="text-center">
      <template v-if="status === 'loading'">
        <div
          class="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-current border-t-transparent"
        />
        <p data-auth-callback-status="loading" class="text-muted-foreground">
          Signing you in...
        </p>
      </template>
      <p
        v-else-if="status === 'success'"
        data-auth-callback-status="success"
        class="text-muted-foreground"
      >
        Redirecting...
      </p>
      <p
        v-else-if="status === 'unauthenticated'"
        data-auth-callback-status="unauthenticated"
        class="text-muted-foreground"
      >
        Authentication failed. Redirecting to login...
      </p>
      <p
        v-else
        data-auth-callback-status="unavailable"
        class="text-muted-foreground"
      >
        Gateway is temporarily unavailable. Redirecting to recovery...
      </p>
    </div>
  </div>
</template>
