// frontend-vue/app/components/workspace/TodoList.vue
<!--
  【文件职责】     折叠展示 thread.values.todos 的真实任务状态。
  【架构位置】     L3 workspace UI adapter
  【主要导出】     默认 TodoList 组件
  【依赖关系】     core/todos
  【边界与注意】   数据所有权在 thread server state；组件只负责 pending/in_progress/completed 展示。
-->

<script setup lang="ts">
import { ref } from "vue";
import { Check, ChevronUp, Circle, ListTodo } from "lucide-vue-next";

import type { Todo } from "@/core/todos";

defineProps<{ todos: Todo[] }>();
const collapsed = ref(true);
</script>

<template>
  <section
    v-if="todos.length"
    class="border-border bg-background overflow-hidden rounded-xl border"
    data-testid="thread-todos"
  >
    <!--
      这一层是 `<button>` + `aria-expanded`。上游 todo-list.tsx:45 原来是一个
      **挂着 onClick 的 `<header>`**：它是这块面板唯一的折叠入口，
      键盘用户完全折不动（WCAG 2.1.1），可访问性树里也读不出展开态。
      **wave 73 两边同改**，`frontend/src/components/workspace/todo-list.tsx`
      已改成同一个形状。

      外观照抄上游那一层：`min-h-8`（上游 32px，本仓原来 `min-h-9` 高 4px）、
      `cursor-pointer`（上游显式写了；Tailwind 4 的 preflight 不给按钮小手，
      本仓这颗此前是箭头）、`transition-all duration-300 ease-out`，
      以及箭头自己的 `text-muted-foreground`——上游那颗箭头是中灰的，
      本仓原来继承前景色，比上游深一档（坑 204：颜色只能从渲染读，不能从 class 推）。
    -->
    <button
      type="button"
      class="bg-accent flex min-h-8 w-full shrink-0 cursor-pointer items-center justify-between px-4 text-sm transition-all duration-300 ease-out"
      :aria-expanded="!collapsed"
      @click="collapsed = !collapsed"
    >
      <span class="text-muted-foreground flex items-center gap-2">
        <ListTodo :size="16" /> To-dos
      </span>
      <ChevronUp
        :size="16"
        class="text-muted-foreground transition-transform duration-300 ease-out"
        :class="collapsed ? '' : 'rotate-180'"
      />
    </button>
    <ul v-if="!collapsed" class="space-y-1 p-3">
      <li
        v-for="(todo, index) in todos"
        :key="`${index}:${todo.content}`"
        class="flex items-start gap-2 text-sm"
        :data-status="todo.status"
      >
        <Check
          v-if="todo.status === 'completed'"
          :size="15"
          class="mt-0.5 text-emerald-600"
        />
        <Circle
          v-else
          :size="15"
          class="mt-0.5"
          :class="
            todo.status === 'in_progress'
              ? 'fill-primary text-primary'
              : 'text-muted-foreground'
          "
        />
        <span
          :class="
            todo.status === 'completed'
              ? 'text-muted-foreground line-through'
              : ''
          "
        >
          {{ todo.content }}
        </span>
      </li>
    </ul>
  </section>
</template>

// frontend/src/components/workspace/todo-list.tsx
import { ChevronUpIcon, ListTodoIcon } from "lucide-react";
import { useState } from "react";

import type { Todo } from "@/core/todos";
import { cn } from "@/lib/utils";

import {
  QueueItem,
  QueueItemContent,
  QueueItemIndicator,
  QueueList,
} from "../ai-elements/queue";

export function TodoList({
  className,
  todos,
  collapsed: controlledCollapsed,
  hidden = false,
  onToggle,
}: {
  className?: string;
  todos: Todo[];
  collapsed?: boolean;
  hidden?: boolean;
  onToggle?: () => void;
}) {
  const [internalCollapsed, setInternalCollapsed] = useState(true);
  const isControlled = controlledCollapsed !== undefined;
  const collapsed = isControlled ? controlledCollapsed : internalCollapsed;

  const handleToggle = () => {
    if (isControlled) {
      onToggle?.();
    } else {
      setInternalCollapsed((prev) => !prev);
    }
  };

  return (
    <div
      className={cn(
        "flex h-fit w-full origin-bottom translate-y-4 flex-col overflow-hidden rounded-t-xl border border-b-0 bg-white backdrop-blur-sm transition-all duration-200 ease-out",
        hidden ? "pointer-events-none translate-y-8 opacity-0" : "",
        className,
      )}
    >
      {/*
        A button, not a clickable <header>. The element carries the only
        collapse/expand affordance for this panel, so a plain header with an
        onClick handler is unreachable by keyboard entirely (WCAG 2.1.1) and
        exposes no state to assistive tech. `aria-expanded` names the state
        the chevron already shows visually.
      */}
      <button
        type="button"
        aria-expanded={!collapsed}
        className={cn(
          "bg-accent flex min-h-8 w-full shrink-0 cursor-pointer items-center justify-between px-4 text-sm transition-all duration-300 ease-out",
        )}
        onClick={handleToggle}
      >
        <div className="text-muted-foreground">
          <div className="flex items-center justify-center gap-2">
            <ListTodoIcon className="size-4" />
            <div>To-dos</div>
          </div>
        </div>
        <div>
          <ChevronUpIcon
            className={cn(
              "text-muted-foreground size-4 transition-transform duration-300 ease-out",
              collapsed ? "" : "rotate-180",
            )}
          />
        </div>
      </button>
      <main
        className={cn(
          "bg-accent flex grow px-2 transition-all duration-300 ease-out",
          collapsed ? "h-0 pb-3" : "h-28 pb-4",
        )}
      >
        <QueueList className="bg-background mt-0 w-full rounded-t-xl">
          {todos.map((todo, i) => (
            <QueueItem key={i + (todo.content ?? "")}>
              <div className="flex items-center gap-2">
                <QueueItemIndicator
                  className={
                    todo.status === "in_progress" ? "bg-primary/70" : ""
                  }
                  completed={todo.status === "completed"}
                />
                <QueueItemContent
                  className={
                    todo.status === "in_progress" ? "text-primary/70" : ""
                  }
                  completed={todo.status === "completed"}
                >
                  {todo.content}
                </QueueItemContent>
              </div>
            </QueueItem>
          ))}
        </QueueList>
      </main>
    </div>
  );
}
